### ISSUE TITLE
Missing Color Texture

### ISSUE THREAD

**Issue by ardissaps** [ianm1647/more-hammers-and-excavators#1]
Some item have only gray color in it : 
https://imgur.com/a/yqB7Igu

**Comment by ianm1647** [comment]
yes i know they have a gray color to them, they aren't textured yet on purpose

**Comment by ardissaps** [comment]
Do you plan on updating it?

**Comment by ianm1647** [comment]
yes eventually, just not right now, ive been taking a break right now
